### ISSUE TITLE
ImportError: cannot import name 'enums'

### ISSUE THREAD

**Issue by steverawlins-zebra** [shoma/spanner-cli#96]
installed spanner-cli on my mac, running python 3.6, but enums import fails:

~ > python --version
Python 3.6.8
~ > spanner-cli --version
Traceback (most recent call last):
  File "/Users/steverawlins/Library/Python/3.6/bin/spanner-cli", line 5, in <module>
    from spannercli import main
  File "/Users/steverawlins/Library/Python/3.6/lib/python/site-packages/spannercli/main.py", line 7, in <module>
    from google.cloud.spanner_v1 import enums
ImportError: cannot import name 'enums'
(reverse-i-search)`instal': pip3 install -U --user spanner-cli

**Comment by shoma** [comment]
It happens in CI.
```
Run pipenv run pylint --rcfile=.pylintrc --verbose --reports=y
  pipenv run pylint --rcfile=.pylintrc --verbose --reports=y
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.10/x64
Using config file /home/runner/work/spanner-cli/spanner-cli/.pylintrc
************* Module spannercli.main
spannercli/main.py:7:0: E0611: No name 'enums' in module 'google.cloud.spanner_v1' (no-name-in-module)
```
https://github.com/shoma/spanner-cli/pull/102/checks?check_run_id=2000774587

**Comment by shoma** [comment]
https://github.com/googleapis/python-spanner/releases/tag/v2.0.0 does not contains `google/cloud/spanner_v1/gapic/enums.py`
https://github.com/googleapis/python-spanner/commit/bf4b27827494e3dc33b1e4333dfe147a36a486b3#diff-f0211708f23ead2312bd22855069c52940d447a666d388086e2908c9e7099442
